Junit4 Assignment
riyaknol11/Junit_Assignment pull request #1
Opened 2023-04-08 10:43 UTC by riyaknol11

2023-04-09 13:00 UTC, anup0060 requested changes

2023-04-09 13:00 UTC, anup0060 commented on Junit4/src/main/java/com/knoldus/StringUtils.java
> +    public String reverse(String string){
string - variable name , not good

2023-04-09 13:00 UTC, anup0060 commented on Junit4/src/test/java/com/knoldus/StringUtilsTest.java
> +    public void reverseStringTestMethodForNonEmptyString(){
testReverseString_givenExpectedInput -- like this, we need to have the name that reflects scenario as suffix.

2023-04-11 18:36 UTC, riyaknol11 reviewed
Modified the naming conventions of methods and added required changes following the reviews

2023-04-12 17:19 UTC, riyaknol11 reviewed
Changes added in StringUtils class file, changes the string variable name

2023-04-12 17:23 UTC, anup0060 approved these changes

2023-04-12 17:24 UTC, merged