Junit5 Assignment
riyaknol11/Junit_Assignment pull request #2
Opened 2023-04-08 11:07 UTC by riyaknol11

2023-04-09 13:02 UTC, anup0060 requested changes

2023-04-09 13:02 UTC, anup0060 commented on Junit5/src/test/java/org/example/PersonTest.java
> +    void testGetEmailWithNullValue() {
testGetEmail_givenNullEmail likewise update all.   _given<Input>

2023-04-11 18:32 UTC, riyaknol11 reviewed
Modified the naming conventions of methods and added required changes following the reviews.

2023-04-12 14:00 UTC, anup0060 approved these changes

2023-04-12 17:23 UTC, merged